Trying hvr's multi GHC travis build.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,30 @@
-language: haskell
-script:
-        - cabal configure --enable-tests
-        - cabal build
-        - cabal test --show-details=always
+env:
+ - GHCVER=7.6.3
+ - GHCVER=7.8.2
 
+before_install:
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH
+
+install:
+ - cabal update
+ - cabal install --dependencies-only --enable-tests --enable-benchmarks
+
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
+script:
+ - cabal configure --enable-tests --enable-benchmarks -v2
+ - cabal build
+ - cabal test --show-details=always
+ - cabal sdist
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+       cabal install "$SRC_TGZ";
+   else
+       echo "expected '$SRC_TGZ' not found";
+       exit 1;
+   fi
